apiVersion: v1
description: public-content-by-concept-api Helm chart for Kubernetes
name: public-content-by-concept-api
version: 1.2.0  # this entry can be left untouched as it is automatically handled by Jenkins pipeline
