# Default values for public-content-by-concept-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/public-content-by-concept-api
  pullPolicy: Always
env: 
  app: 
    port: "8080" 
  graphite: 
    prefix: "coco.services.k8s.public-content-by-concept-api"
  cache: 
    duration: "30s" 
resources:
  limits:
    memory: 256Mi


